# Site settings
title: Zachary Hervieux-Moore
description: "A blog by Zachary Hervieux-Moore"
url: "http://www.hervature.com/blog"
author:
  name: "Zachary Hervieux-Moore"
  email: "zhm@princeton.com"
  url: "http://www.hervature.com"
gems:
  - jekyll-paginate

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
